label sayori:
    #Hızlı son 1
    scene black
    stop music fadeout 1.0
    play music mend fadein 1.5
    show sayori 1bb zorder 1 at t11
    s "Senin ismin [player] değil."
    s "Senin ismin [usr]."
    mc_usr "Nasıl bildin peki?"
    s "Geçmişten gelen birşey bu."
    s 1bu "Ben isteyerek böyle olmadım..."
    s "Gerçekten isteyerek böyle olmadım..."
    mc_usr "Tamam Sayori."
    mc_usr "Ağlamana gerek yok."
    s "B-Bu geçmişten gelen birşey."
    s "Ailem"
    s "Beni buna ailem zorladı."
    s "Herşey onlardan dolayı oldu."
    s "Ben öyle olmak istemedim."
    s "Herşey o adamın yüzünden oldu."
    mc_usr "O adam?"
    s "Babam..."
    s "O adam anneme hiç iyi davranmadı."
    mc_usr "Neden?"
    s "Senin ile çok uzun yıllardır arkadaşız."
    s "Sen bile bazı şeyleri bilmiyorsun." 
    s "O adam daha ben doğmadan annemi terk etmiş."
    s "Bana hem annelik hemde babalık yaptı ama bunca yükün altına girerek daha çok yoruluyordu."
    s "Annem eve hep geç saatlerde gelir ve sürekli yorgun olurdu."
    s "Anneme kendimi ifade etmekten çekinir oluştum."
    s "Neşeli görünmeye çalışarak annemi daha fazla üzmemeye ve yormamak için sürekli sahte bir şekilde gülümserdim."
    s "Ama benim içimdeki yanlızlık hep içimde derinleşti."
    s "İlkokul zamanlarında, sınıf arkadaşlarımın hemen hemen hepsini babası almaya gelirdi ve onların hafta sonu ile ilgili yaptıkları planları duyadım."
    s "Anneme babamın nerede olduğunu sorduğumda ise burkuk bir şekilde 'O uzun bir iş gezisinde.' derdi."
    s "Ben bu arkadaşlarımın ailesi ile iyi vakit geçirmelerini duydukça ve gördükçe canım daha da sıkılıyor ve iletişim kuramaz oluyordum."
    s "O zamanlar benim için bu inanılmaz uzak bir hayaldi."
    s "Bu görüntüler ben daha küçük olduğum için çok ağır gelmişti."
    s "Okuldan eve döndüğümde annem ile vakit geçirmektense kitaplar okurdum. Çünkü bu acı gerçeklikten kaçabilmem için te çareydi ama bu benim için yetersiz geliyordu."
    s "Annemle konuşmak istediğimde annem ya çok yorgun olurdu yada iş stresi nedeniyle benim ile çok ilgilenemezdi."
    s "Bu içsel sıkıntılar her geçen gün artıyordu. Dışarıya karşı neşeli görünmeye çalışıyordum ama bu beni mental olarak çok yoruyordu."
    s "Her geçen gün çağresizik artıyordu."
    s "Arkadaşlık kuramamaya başladım. Çocukların yaptığı faaliyetler bana keyif vermemeye başladı."
    s "İlkokulun sonlarına doğru bir gece annem odamda boş gözlerle tavana baktığımı gördü. Bu acı dahada derinleşmişti."
    s "Herşey benim için sarpa sarmıştı ve hayatı sorgularken annem odama girdi."
    s "Odama girdi ve beni sadece kucakladı. Bende büyük bir hüzünle anneme sarıldım."
    s "O gece geçici bir rahatlığa ermiştim."
    s "Yıllar hep aynı geçmeye başladı. Geceleri ruhsuzluk, gündüzleri ise enerjik ve neşeli."
    s "Gündüz hayatından nefret etmeye başlamıştım."
    s "Ortaokulun son zamanlarında bana telefon alındı."
    s "Sosyal medyaya gömülmeye başladım."
    s "Arkadaşların ile takipleşmeye başladıktan sonra bu benim için daha da sıkıntı olmaya başladı."
    s "Arkadaşlarımın mutlu ale karelerini görmek beni daha çok yoruyordu." 
    s "Sürekli mutlu görünmeye çalıştığım için- {nw}"
    mc_usr "Tüm bunları-{w=1} Tüm bunları bana anlatmadın."
    mc_usr "Tüm bunları neden bana anlatmadın."
    show sayori 5bu zorder 1 at t11
    s "Zaten yeteri kadar derdin var. Birde beniki eklenmesin diye."
    mc_usr "Sayori..."
    mc_usr "Biz doğduğumuzdan beri arkadaşız."

    jump end_easteregg
    return
